// Generated by https://quicktype.io

export class CategoryResponse {
    // eslint-disable-next-line @typescript-eslint/naming-convention
    id: number;
    // eslint-disable-next-line @typescript-eslint/naming-convention
    nombre_categoria: string;
    // eslint-disable-next-line @typescript-eslint/naming-convention
    descripcion_categoria: string;
    // eslint-disable-next-line @typescript-eslint/naming-convention
    estado: string;

    constructor(data: { [key: string]: unknown }) {
        this.id = data['id'] as number;
        this.nombre_categoria = data['nombre_categoria'] as string;
        this.descripcion_categoria = data['descripcion_categoria'] as string;
        this.estado = data['estado'] as string;
    }
}
