// Generated by https://quicktype.io

export interface Orders {
    id:             number;
    orderDate:      string;
    hourDate:       string;
    idClient:       number;
    table:          number;
    orderState:     string;
    //dishesList:  DishesList[];
    totalOrder:     number;
    paymentMethod:  string;
}

export interface DishesList {
    idMenu:        number;
    dishesNumber:  number;
}
